if: commit_message !~ /(Deploy race-on)/
dist: bionic
language: python
install:
  - pip3 install sphinx
script:
  - make html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  keep_history: true
  on:
    branch: master
