dist: bionic
language: python
install:
  - pip3 install sphinx
script:
  - make html
  - touch build/html/.nojekyll
deploy:
  local_dir: build/html
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  on:
    branch: master
